name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0' # Use a specific stable version
          
      - name: Install dependencies
        run: |
          cd mobile_app
          flutter clean
          flutter pub get
          
      - name: Build Web
        run: |
          cd mobile_app
          flutter build web --release --base-href "/aibuddy-CoMPAS/"
          
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mobile_app/build/web
          force_orphan: true
